### ISSUE TITLE
Publish new version to avoid duplicate installs of SilverStripe Shop

### ISSUE THREAD

**Issue by jordanmkoncz** [silvershop/silvershop-geocoding#10]
The most recent published version of this package, `1.2.3`, is almost 2 years old and has a dependency on the old `"burnbright/silverstripe-shop": "*"` which causes a duplicate install of SilverStripe Shop for any module that includes `silvershop/silvershop-geocoding` as a dependency.

Please publish a new version based on the latest commit to fix this.

**Comment by jordanmkoncz** [comment]
See https://github.com/silvershop/silvershop-shipping/issues/30 for an example of where this is causing problems.

**Comment by wilr** [comment]
Thanks @jordanmkoncz, tagged 2.0.0

**Comment by jordanmkoncz** [comment]
@wilr Has the new version been published to Packagist yet? I'm getting an error when trying to install `silvershop/shipping` (which depends on this module):

`silvershop/shipping dev-master requires silvershop/geocoding ~2.0 -> no matching package found.`
